import { ExperimentListItem } from "@/entities/experiment/model/types";

export const seedCategories = [
  { id: "all", name: "All", color: "#5b8def", count: 12 },
  { id: "ui", name: "UI Components", color: "#60a5fa", count: 4 },
  { id: "landing", name: "Landing Pages", color: "#e87461", count: 3 },
  { id: "data", name: "Data Viz", color: "#4ade80", count: 2 },
  { id: "form", name: "Forms", color: "#a78bfa", count: 2 },
  { id: "email", name: "Email Templates", color: "#facc15", count: 1 },
] as const;

export const seedExperiments: ExperimentListItem[] = [
  {
    id: "dashboard-widget-comparison",
    title: "Dashboard Widget Comparison",
    description:
      "Compare how different LLMs generate a responsive analytics dashboard card with chart integration and real-time data display.",
    status: "active",
    categoryId: "ui",
    categoryName: "UI Components",
    categoryColor: "#60a5fa",
    tags: ["dashboard", "charts", "responsive"],
    promptCount: 3,
    resultCount: 8,
    avgRating: 7.4,
    createdAt: "2026-01-15T10:00:00.000Z",
    updatedAt: "2026-03-23T08:00:00.000Z",
    createdLabel: "Jan 15, 2026",
    updatedLabel: "2 hours ago",
  },
  {
    id: "saas-hero-section-variants",
    title: "SaaS Hero Section Variants",
    description:
      "Testing hero section generation with gradient backgrounds, CTA placement, and animated illustrations across models.",
    status: "active",
    categoryId: "landing",
    categoryName: "Landing Pages",
    categoryColor: "#e87461",
    tags: ["hero", "saas", "animation"],
    promptCount: 2,
    resultCount: 10,
    avgRating: 8.1,
    createdAt: "2026-01-12T10:00:00.000Z",
    updatedAt: "2026-03-23T05:00:00.000Z",
    createdLabel: "Jan 12, 2026",
    updatedLabel: "5 hours ago",
  },
  {
    id: "interactive-chart-rendering",
    title: "Interactive Chart Rendering",
    description:
      "Evaluating Chart.js vs D3 code generation quality across Claude, GPT-4, and Gemini for complex multi-series datasets.",
    status: "completed",
    categoryId: "data",
    categoryName: "Data Viz",
    categoryColor: "#4ade80",
    tags: ["chart.js", "d3", "interactive"],
    promptCount: 4,
    resultCount: 12,
    avgRating: 8.6,
    createdAt: "2025-12-28T10:00:00.000Z",
    updatedAt: "2026-03-20T10:00:00.000Z",
    createdLabel: "Dec 28, 2025",
    updatedLabel: "3 days ago",
  },
  {
    id: "multi-step-form-wizard",
    title: "Multi-Step Form Wizard",
    description:
      "How well can LLMs build accessible multi-step form wizards with validation, progress indicators, and error handling?",
    status: "draft",
    categoryId: "form",
    categoryName: "Forms",
    categoryColor: "#a78bfa",
    tags: ["forms", "a11y", "validation"],
    promptCount: 1,
    resultCount: 0,
    avgRating: null,
    createdAt: "2026-01-20T10:00:00.000Z",
    updatedAt: "2026-03-22T10:00:00.000Z",
    createdLabel: "Jan 20, 2026",
    updatedLabel: "1 day ago",
  },
  {
    id: "transactional-email-layouts",
    title: "Transactional Email Layouts",
    description:
      "Comparing LLM-generated HTML email templates for order confirmations, password resets, and onboarding sequences.",
    status: "active",
    categoryId: "email",
    categoryName: "Email Templates",
    categoryColor: "#facc15",
    tags: ["email", "html-email", "transactional"],
    promptCount: 2,
    resultCount: 6,
    avgRating: 5.8,
    createdAt: "2026-01-08T10:00:00.000Z",
    updatedAt: "2026-03-23T01:00:00.000Z",
    createdLabel: "Jan 8, 2026",
    updatedLabel: "12 hours ago",
  },
  {
    id: "pricing-page-showdown",
    title: "Pricing Page Showdown",
    description:
      "Full pricing page with toggle, feature comparison table, and FAQ accordion tested across five models.",
    status: "completed",
    categoryId: "landing",
    categoryName: "Landing Pages",
    categoryColor: "#e87461",
    tags: ["pricing", "toggle", "comparison"],
    promptCount: 2,
    resultCount: 10,
    avgRating: 7.9,
    createdAt: "2025-12-15T10:00:00.000Z",
    updatedAt: "2026-03-16T10:00:00.000Z",
    createdLabel: "Dec 15, 2025",
    updatedLabel: "1 week ago",
  },
];